Update app workflow to install the native toolchain if the project requires it

diff --git a/.github/workflows/skip-app.yml b/.github/workflows/skip-app.yml
--- a/.github/workflows/skip-app.yml
+++ b/.github/workflows/skip-app.yml
@@ -58,6 +58,7 @@ jobs:
           submodules: 'recursive'
 
       - name: Setup
+        id: setup
         run: |
           # convert "refs/tags/1.0.0" to "1.0.0"
           # and "refs/heads/main" to "main"
@@ -76,6 +77,14 @@ jobs:
 
           # update Skip.env to set build number to the git commit count
           sed -i '' "s;PRODUCT_VERSION = .*;PRODUCT_VERSION = $(git rev-list --count HEAD);g" Skip.env
+
+          # check whether any of the skip.yml files in the project
+          # presume the native toolchain 
+          yq -e '.skip.mode' Sources/*/Skip/skip.yml >> /dev/null && echo "native-toolchain=required" >> $GITHUB_OUTPUT || echo "Native toolchain not needed"
+
+      - name: Install Swift Android Toolchain
+        if: ${{ steps.setup.outputs.native-toolchain == 'required' }}
+        run: brew install skiptools/skip/swift-android-toolchain@6.0
 
       - name: Verify Skip App
         run: skip verify || skip verify --verbose
