Add inputs.android-native-disabled to disable native Android build

diff --git a/.github/workflows/skip-framework.yml b/.github/workflows/skip-framework.yml
--- a/.github/workflows/skip-framework.yml
+++ b/.github/workflows/skip-framework.yml
@@ -55,6 +55,10 @@ on:
         required: false
         type: boolean
         default: true
+      android-native-disabled:
+        required: false
+        type: boolean
+        default: false
       emulator-api-level:
         required: false
         type: string
@@ -116,9 +120,12 @@ jobs:
           echo "android-arch=$(uname -m | sed 's/arm64/arm64-v8a/')" >> $GITHUB_OUTPUT
           # disable user confirmation to process macros
           defaults write com.apple.dt.Xcode IDESkipMacroFingerprintValidation -bool YES
-          # check whether we use skip-bridge and so need the Android toolchain 
-          SKIP_BRIDGE=1 swift package resolve
-          test -d Sources/SkipBridge || jq -e '.pins | any(.identity == "skip-bridge")' Package.resolved >> /dev/null && echo "native-toolchain=required" >> $GITHUB_OUTPUT || echo "Swift Android toolchain not required"
+
+          if [[ ${{ inputs.android-native-disabled }} != true ]]; then
+            # check whether we use skip-bridge and so need the Android toolchain
+            SKIP_BRIDGE=1 swift package resolve
+            test -d Sources/SkipBridge || jq -e '.pins | any(.identity == "skip-bridge")' Package.resolved >> /dev/null && echo "native-toolchain=required" >> $GITHUB_OUTPUT || echo "Swift Android toolchain not required"
+          fi
 
       - name: Swift Android Toolchain Build
         id: setup-toolchain
